/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package card_game;

import card_game.builders.PlayerBuilder;
import card_game.data.Suit;
import org.junit.Before;
import org.junit.Test;

import java.util.ArrayList;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.Assert.*;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

public class AppTest {

    public ArrayList<Player> players;
    public Player player;

    private App  app  = mock(App.class);
    private Deck deck = mock(Deck.class);

    @Before
    public void setup() {
        players = PlayerBuilder.multiplePlayersBuilder();
        player = PlayerBuilder.singlePlayerBuilder();
    }

    @Test
    public void testPlay_ShouldReturnAWinne_WhenATieOccurs() {

        when(deck.cardsRemaining()).thenReturn(40,38);
        when(deck.dealCard()).thenReturn(Card.buildCard(2, Suit.CLUBS),
                Card.buildCard(2, Suit.DIAMONDS),
                Card.buildCard(9, Suit.SPADES),
                Card.buildCard(10, Suit.DIAMONDS));

        Player player = app.play(players, deck);
        assertThat(player.getDealtCard(4).getValue(), equalTo(10));
    }
}


